### ISSUE TITLE
Vuln --init fails

### ISSUE THREAD

**Issue by yyosioka** [eliasgranderubio/dagda#85]
I ran the docker-compose.yml file and got this.

The execution result is as follows.
![dagda1](https://user-images.githubusercontent.com/62535924/87782615-d6441d00-c86d-11ea-92b6-e556b3dce581.JPG)

$docker exec -it dagda python3 dagda.py vuln --init
The execution result is as follows.
![dagda2](https://user-images.githubusercontent.com/62535924/87782630-df34ee80-c86d-11ea-898b-82ea11dcbdcd.JPG)

$ docker exec -it dagda python3 dagda.py vuln --init_status

It will fail with an error.
![dagda3](https://user-images.githubusercontent.com/62535924/87782648-e52acf80-c86d-11ea-9416-0528e6d3dacb.JPG)

 the following information:

OS: [Ubuntu]
OS Version: [18.0.4]
Python version: [Python 3.6.9]
Docker version [Docker version 19.03.12]

**Comment by groboclown** [comment]
This is because the code pulls the file `https://www.redhat.com/security/data/oval/rhsa.tar.bz2`, which is now deprecated and empty.  This causes the retrieved lists to be empty, and MongoDB fails to insert the empty list.

The short-term patch is to add a check condition in `mongodb_driver.py` that does a simple "if" check to ensure the lists aren't empty on insert.  One longer-term fix is to switch the URL to the now recommended OVAL single XML file bundle, as described at https://www.redhat.com/security/data/metrics/.  This requires a bit more work.

**Comment by eliasgranderubio** [comment]
I've just updated Dagda to work with Python 3.8.
